version: '3'
services:
  postgresql:
    container_name: twitter-pipeline-postgresql
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - ./scheme.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
